# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_motiondetectclassifiy(object):
    def setupUi(self, motiondetectclassifiy):
        motiondetectclassifiy.setObjectName("motiondetectclassifiy")
        motiondetectclassifiy.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(motiondetectclassifiy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 211, 20))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(150, 50, 331, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.openNewClass = QtWidgets.QPushButton(self.centralwidget)
        self.openNewClass.setGeometry(QtCore.QRect(10, 150, 131, 25))
        self.openNewClass.setObjectName("openNewClass")
        self.SaveThisFrames = QtWidgets.QPushButton(self.centralwidget)
        self.SaveThisFrames.setGeometry(QtCore.QRect(480, 150, 131, 31))
        self.SaveThisFrames.setObjectName("SaveThisFrames")
        self.emptyFrame = QtWidgets.QPushButton(self.centralwidget)
        self.emptyFrame.setGeometry(QtCore.QRect(460, 450, 89, 25))
        self.emptyFrame.setObjectName("emptyFrame")
        self.prevFrame = QtWidgets.QPushButton(self.centralwidget)
        self.prevFrame.setGeometry(QtCore.QRect(190, 450, 89, 25))
        self.prevFrame.setObjectName("prevFrame")
        self.NextFrame = QtWidgets.QPushButton(self.centralwidget)
        self.NextFrame.setGeometry(QtCore.QRect(370, 450, 89, 25))
        self.NextFrame.setObjectName("NextFrame")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(280, 450, 89, 25))
        self.Stop.setObjectName("Stop")
        self.LoadNewVideo = QtWidgets.QPushButton(self.centralwidget)
        self.LoadNewVideo.setGeometry(QtCore.QRect(60, 450, 131, 25))
        self.LoadNewVideo.setObjectName("LoadNewVideo")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(490, 290, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 271, 221))
        self.graphicsView_2.setObjectName("graphicsView_2")
        motiondetectclassifiy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(motiondetectclassifiy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        motiondetectclassifiy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(motiondetectclassifiy)
        self.statusbar.setObjectName("statusbar")
        motiondetectclassifiy.setStatusBar(self.statusbar)

        self.retranslateUi(motiondetectclassifiy)
        QtCore.QMetaObject.connectSlotsByName(motiondetectclassifiy)

    def retranslateUi(self, motiondetectclassifiy):
        _translate = QtCore.QCoreApplication.translate
        motiondetectclassifiy.setWindowTitle(_translate("motiondetectclassifiy", "MainWindow"))
        self.label.setText(_translate("motiondetectclassifiy", "Motion Detector And classifier"))
        self.openNewClass.setText(_translate("motiondetectclassifiy", "open new class"))
        self.SaveThisFrames.setText(_translate("motiondetectclassifiy", "save this frames to"))
        self.emptyFrame.setText(_translate("motiondetectclassifiy", "Empty Frame"))
        self.prevFrame.setText(_translate("motiondetectclassifiy", "prev. frame"))
        self.NextFrame.setText(_translate("motiondetectclassifiy", "next frame"))
        self.Stop.setText(_translate("motiondetectclassifiy", "stop"))
        self.LoadNewVideo.setText(_translate("motiondetectclassifiy", "Load new Video"))
